### ISSUE TITLE
# Result 1.0

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#1]
## comparison in percent
----------
As a [user] of the App  I want to get an displayed result how ecofriendly my Website is, so that i get an estimated overview how much CO2 my Website consumes (in comparison to other websites)

## Acceptance Criteria
- [ ] Show an Result (in percent) how much Co2 the Website  emits  in comparison to the other tested sites

## Tasks
- [ ] Use The API to deliver an result in %
> 50 % cleaner than
< 50 % dirtier than the avarge of the tested sites 
- [ ] Create an Textarea that drops out the result
