### ISSUE TITLE
## Add Nav Bar

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#10]
## Navbar
----------
As a [user] of the App  I want to get an Navigation Bar displayed.
So that i can navigate easier through the app

## Acceptance Criteria 
- [x] Add an navbar
- [ ] Add a Home attribute

## Tasks
- [x] Create a navbar
- [ ] Link the Home Attribute to the Startpage
-
