### ISSUE TITLE
# Home 1.0

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#2]
## Input for Url
----------
As a [user] of the App  I want to be able to type in the URL of my Website,
So that it is checked in terms of sustainability.

## Acceptance Criteria 
- [ ] Add an short intro text
- [ ] Add an input field  where the user can type in his/her url

## Tasks
- [ ] Create an Input Field for the url the user
