### ISSUE TITLE
## active linklist green hosting providers

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#22]
As a user i want the green hosting providers to be an active link. So that i can click directly on them. 

# Acceptance Criteria 
- [ ] Add active Links plus name of each provider
- [ ] Ad a function that the user get forwarded

# Tasks
- [ ] add functional active links
- [ ] add names of providers
