### ISSUE TITLE
# create a landingpage

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#23]
as a user i want to get an landingpage displayed wich give me infos about the possibilities of the app

## Acceptance Criteria 
- [ ] Add a landingpage
- [ ] Add short explanation

## Tasks
- [ ] Create a landingpage
- [ ] give the possibility to link to the calculator
- [ ] give the possibility to link to the green host search
