### ISSUE TITLE
# Home 1.2

### ISSUE THREAD

**Issue by Carolin-Weitkamp** [Carolin-Weitkamp/capstone-project#3]
## Check Button / Fetch
----------
As a [user] of the App  I want to be able to send an request, so that my website will be checked by the App in terms of sustainability.

## Acceptance Criteria 

Show Landingpage plus:
- [ ] an clickable “CHECK” button
- [ ] add an short explanation / respectively conditions of use  / how it works

## Tasks
- [ ] Ccreate an “CHECK” button
- [ ] Fetch the app with the api
